### ISSUE TITLE
请问这个是要配合什么用

### ISSUE THREAD

**Issue by yamakaze123** [jerryshell/bili-blocklist-sync#4]
卡在bbs pull拉取黑名单列表这了，这个是要配合什么用吗

**Comment by jerryshell** [comment]
我编译并上传了 Windows 的二进制可执行文件，并且更新了 README 的使用说明，现在你按照新的使用说明去做应该就没问题了，我这里已经测试过了

**Comment by yamakaze123** [comment]
谢谢你，成功拉取了账号黑名单，但是同步到另一个账号时没有反应，是不是要在config里填写两个账号的data和jct？我看之前的默认有两个位置，打包后只有一个了

**Comment by jerryshell** [comment]
`config.json` 的 `cookie_list` 是一个数组，你填多少个都行

**Comment by yamakaze123** [comment]
我填了两个账号，拉取后同步完点主页显示这个，过一阵子恢复后黑名单并没有变化
![QQ截图20240614125415](https://github.com/jerryshell/bili-blocklist-sync/assets/95601982/97ddcbd4-6640-4be9-910c-9b1c937c3a32)

**Comment by jerryshell** [comment]
我更新了 v0.1.1 版本，增加了睡眠时间，现在同步速度会慢一点，但是应该都能成功了

**Comment by yamakaze123** [comment]
2m2024-06-14T05:39:08.313216Z[0m [32m INFO[0m [2mbbs[0m[2m:[0m "{\"code\":-352,\"message\":\"-352\",\"ttl\":1}\n"
[2m2024-06-14T05:39:29.417082Z[0m [31mERROR[0m [2mbbs[0m[2m:[0m reqwest::Error {
    kind: Request,
    url: Url {
        scheme: "https",
        cannot_be_a_base: false,
        username: "",
        password: None,
        host: Some(
            Domain(
                "api.bilibili.com",
            ),
        ),
        port: None,
        path: "/x/relation/modify",
        query: None,
        fragment: None,
    },
    source: hyper_util::client::legacy::Error(
        SendRequest,
        hyper::Error(
            Io,
            Custom {
                kind: UnexpectedEof,
                error: "peer closed connection without sending TLS close_notify: https://docs.rs/rustls/latest/rustls/manual/_03_howto/index.html#unexpected-eof",
            },
        ),
    ),
}
[2m2024-06-14T05:39:29.418454Z[0m [32m INFO[0m [2mbbs[0m[2m:[0m > Press [Enter] to close terminal <

这是最后的报错内容，

**Comment by yamakaze123** [comment]
顺便一提我是一个登录在谷歌浏览器，一个账号登录在360极速浏览器的，是因为这个原因同步不了吗？

**Comment by jerryshell** [comment]
这个报错应该是同步黑名单时候达到了 Bilibili 的 API 速率限制，`config.json` 的 `sleep_ms` 代表睡眠时间，单位是毫秒，你可以试着把这个值改大一点。我这边 2 个账号同步大概 100 个黑名单是没问题的。

**Comment by jerryshell** [comment]
关闭不活跃 issue
